In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('store.xlsx')
df.head()

,transaction_id,store_id,cashier_id,product_id,product_category,unit_price,quantity,transaction_time,loyalty_member,payment_method,discount,total_amount
0,T100000,S6,C131,P828,Clothing,454.86,5,2025-04-28,Yes,UPI,0.51,2262.70
1,T100001,S10,C367,P666,Grocery,296.22,2,2024-06-19,Yes,Debit Card,10.94,527.63
2,T100002,S7,C257,P314,Grocery,488.44,3,2024-10-30,No,Mobile Wallet,3.20,1418.43
3,T100003,S21,C161,P190,Personal Care,461.66,8,2025-01-25,Yes,Cash,15.48,3121.56
4,T100004,S46,C484,P451,Personal Care,374.91,3,2023-12-11,Yes,Credit Card,16.14,943.20

Total Revenue

In [ ]:
revenue_per_category = (
    df.groupby('product_category')['total_amount']
    .sum()
    .reset_index()
    .sort_values(by='total_amount', ascending=False)
)

revenue_per_category

  product_category  total_amount
2      Electronics    4050188.08
6           Snacks    3940318.50
4        Household    3863832.66
0        Beverages    3860551.46
1         Clothing    3835744.08
5    Personal Care    3824132.64
3          Grocery    3743254.96

Tren Penjualan per Bulan

In [ ]:
df['month'] = df['transaction_time'].astype(str).str[:7]
monthly_sales = (
    df.groupby('month')['total_amount']
    .sum()
    .reset_index()
    .sort_values('month')
)

monthly_sales

      month  total_amount
0   2023-09     759086.47
1   2023-10    1101308.68
2   2023-11    1114871.25
3   2023-12    1184920.96
4   2024-01    1157718.12
5   2024-02    1141639.00
6   2024-03    1182514.71
7   2024-04    1148011.83
8   2024-05    1106147.87
9   2024-06    1086258.00
10  2024-07    1248127.76
11  2024-08    1099582.66
12  2024-09    1066116.92
13  2024-10    1143037.07
14  2024-11    1100846.34
15  2024-12    1045186.94
16  2025-01    1182218.97
17  2025-02    1123590.65
18  2025-03    1184895.03
19  2025-04    1107829.87
20  2025-05    1132455.41
21  2025-06    1041964.69
22  2025-07    1118479.05
23  2025-08    1160342.10
24  2025-09     380872.03

In [ ]:
df['year'] = df['transaction_time'].astype(str).str[:4]
yearly_sales = (
    df.groupby('year')['total_amount']
    .sum()
    .reset_index()
    .sort_values('year')
)

yearly_sales

   year  total_amount
0  2023    4160187.36
1  2024   13525187.22
2  2025    9432647.80

In [ ]:
top_5_stores = (
    df.groupby('store_id')['total_amount']
    .sum()
    .reset_index()
    .sort_values(by='total_amount', ascending=False)
    .head(5)
)

top_5_stores

   store_id  total_amount
38      S44     613764.68
22       S3     608694.85
15      S23     595743.23
40      S46     590555.19
11       S2     585960.80

In [ ]:
top_product_categories = (
    df.groupby('product_category')['total_amount']
    .sum()
    .reset_index()
    .sort_values(by='total_amount', ascending=False)
)

top_product_categories

  product_category  total_amount
2      Electronics    4050188.08
6           Snacks    3940318.50
4        Household    3863832.66
0        Beverages    3860551.46
1         Clothing    3835744.08
5    Personal Care    3824132.64
3          Grocery    3743254.96

In [ ]:
payment_preferences = (
    df['payment_method']
    .value_counts()
    .reset_index()
)

payment_preferences.columns = ['payment_method', 'total_transactions']
payment_preferences

  payment_method  total_transactions
0    Credit Card                4725
1           Cash                4649
2  Mobile Wallet                4648
3            UPI                4612
4     Debit Card                4466

In [ ]:
discount_analysis = (
    df.groupby('discount')
    .agg(
        total_revenue=('total_amount', 'sum'),
        total_quantity=('quantity', 'sum'),
        total_transactions=('transaction_id', 'count')
    )
    .reset_index()
    .sort_values('discount')
)

discount_analysis

      discount  total_revenue  total_quantity  total_transactions
0         0.00        5104.16              28                   6
1         0.01        2069.03              29                   7
2         0.02        8984.49              43                   8
3         0.03       15253.48              47                   7
4         0.04        9141.32              45                   7
...        ...            ...             ...                 ...
2994     29.96       10653.22              66                  10
2995     29.97        8092.31              42                  11
2996     29.98        4360.82              41                  11
2997     29.99       14359.84              65                  11
2998     30.00        5334.41              25                   5

[2999 rows x 4 columns]

In [ ]:
product_performance = (
    df.groupby('product_category')['quantity']
    .sum()
    .reset_index()
    .sort_values(by='quantity', ascending=False)
)

product_performance

  product_category  quantity
2      Electronics     18858
5    Personal Care     18278
6           Snacks     18228
0        Beverages     18191
4        Household     18175
1         Clothing     18072
3          Grocery     17530

In [ ]:
summary = {
    'Total Revenue': df['total_amount'].sum(),
    'Total Transactions': df['transaction_id'].nunique(),
    'Total Products': df['product_id'].nunique(),
    'Total Stores': df['store_id'].nunique()
}

pd.DataFrame(summary.items(), columns=['Metric', 'Value'])

               Metric        Value
0       Total Revenue  27118022.38
1  Total Transactions     23100.00
2      Total Products      1000.00
3        Total Stores        50.00